
services:
  frontend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: blood-donation-frontend-dev  # Define a custom container name
    
    expose:
      - "3000"  # Expose the Vite development server on port 3000
    networks:
      - blood-link
    volumes:
      - shared-data:/shared
    environment:
      - VITE_REACT_APP_API_URL=https://localhost/api/v1/

    command: ["npm", "run", "dev"] # Start the Vite development server
    tty: true  # Allocate a pseudo-TTY for the container

networks:
  blood-link:
    external: true

volumes:
  shared-data: